name: Schema
document_path: schema
type: object
required: true
entity_name: contract_schema
entity_type: table
entity_schema: data_contracts
description: This entity describes the schema of the data contract.
odcs_reference: "https://bitol-io.github.io/open-data-contract-standard/v3.1.0/schema/"
properties:
  - name: id
    odcs_schema: "$defs.StableId"
    alias: id
    type: StableId
    primary_key: true
  - name: name
    odcs_schema: "$defs.SchemaElement.properties.name"
    type: StructuredName
  - name: physical_type
    odcs_schema: "$defs.SchemaElement.properties.physicalType"
    enum: ["view", "table"]
  - name: description
    odcs_schema: "$defs.SchemaElement.properties.description"
  - name: business_name
    odcs_schema: "$defs.SchemaElement.properties.businessName"
    type: string
  - name: authoritative_definitions
    type: AuthoritativeDefinitions
    alias: authoritativeDefinitions
    required: false
    odcs_schema: "$defs.AuthoritativeDefinitions"
  - name: tags
    required: false
    type: Tags
    odcs_schema: "$defs.Tags"
    alias: tags
  - name: custom_properties
    type: CustomProperties
    odcs_schema: "$defs.CustomProperties"
    required: false
  - name: physical_name
    odcs_schema: "$defs.SchemaObject.properties.physicalName"
    type: StructuredName
  - name: data_granularity_description
    odcs_schema: "$defs.SchemaObject.properties.dataGranularityDescription"
  - name: flow_type
    type: string
    description: Database Name.
    alias: flowType
    enum: [ "input", "output", "transform", "map" ]
  - name: server_id
    odcs_schema: "$defs.StableId"
    alias: serverId
    type: StableId
    primary_key: false
    unique: true
    description: Server Id.
  - name: contract_id
    type: StableId
    description: Contract Id.
    alias: contractId
    required: false
  - name: contract_record_hash
    type: string
    description: Contract Record Hash.
    alias: contractRecordHash
    required: false
